### ISSUE TITLE
Can you support python 2

### ISSUE THREAD

**Issue by humiaozuzu** [ViktorStiskala/raven-bash#1]
As we cannot install python 3 in our production servers.

**Comment by ViktorStiskala** [comment]
Not supporting Python 2 was mainly for time reasons. However, feel free to fork it and send a pull request.

**Comment by Rylon** [comment]
Ditto! I cloned and installed the egg locally and it seemed to mostly work in 2.7 @humiaozuzu were you able to get it to work?

**Comment by humiaozuzu** [comment]
@Rylon Good. But we are using cron-sentry now

**Comment by Rylon** [comment]
Ah yes, I did see that, but the system I have in mind has a lot of moving parts and I'd like to avoid wrapping the various commands, which is what lead me to this project instead :D

@hareevs Would you maybe still consider merging and pushing the update to PyPi however?

Thanks again!

**Comment by ViktorStiskala** [comment]
Closing this issue as this was already merged.
